// Code generated by ogen, DO NOT EDIT.

package aapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetAccountBalance implements getAccountBalance operation.
//
// Returns geven address balance in all requested chains.
//
// POST /accountBalance
func (UnimplementedHandler) GetAccountBalance(ctx context.Context, req *BalancesRequest) (r *BalancesReply, _ error) {
	return r, ht.ErrNotImplemented
}
